spring:
  profiles:
    include: secret
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        #default_batch_fetch_size: 1000 #최적화 옵션

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  org.hibernate.type.descriptor.sql.BasicBinder: trace
  org.hibernate.orm.jdbc.bind: trace

server:
  port: 9090
#  address: 0.0.0.0

app:
  batch:
    daily-orders:
      enabled: true
      max-per-day: 30
      cron: "0 0 3 * * *"
      start-hour: 8
      end-hour: 20
      min-lines-per-order: 1
      max-lines-per-order: 3