spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/kiosk2
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    sql:
      init:
        mode: always
        schema-locations: classpath:schema.sql
        data-locations: classpath:data.sql

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        #default_batch_fetch_size: 1000 #최적화 옵션

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  org.hibernate.type.descriptor.sql.BasicBinder: trace
  org.hibernate.orm.jdbc.bind: trace

server:
  port: 8081
  address: 0.0.0.0
jwt:
  secret: your-super-secret-jwt-key-that-is-long-enough-for-hs512-algorithm-and-must-be-at-least-512-bits-long-which-means-64-characters-minimum
  expiration: 86400000 # 24시간 (밀리초)